name: Playwright Tests
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Set datetime variable
      id: datetime
      run: echo "current_datetime=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./playwright-report
        destination_dir: "run-${{ env.current_datetime }}"

    - name: Update index.html
      run: |
          # Create a list of directories and generate index.html
          mkdir update-html
          echo "<html><body><h1>Directory Listing</h1><ul>" > update-html/index.html
          for dir in run-*/ ; do
              if [ -d "$dir" ]; then
                  echo "<li><a href=\"$dir\">$dir</a></li>" >> update-html/index.html
              fi
          done
          echo "</ul></body></html>" >> update-html/index.html
          
    - name: Deploy update index.html to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: .update-html
